// Generated by https://quicktype.io

export interface PlacesResponse {
  type: string;
  query: string[];
  features: Feature[];
  attribution: string;
}

export interface Feature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: Properties;
  text_es: string;
  place_name_es: string;
  text: string;
  place_name: string;
  center: number[];
  geometry: Geometry;
  context: Context[];
}

export interface Context {
  id: ID;
  text_es: string;
  text: string;
  wikidata?: Wikidata;
  language_es?: Language;
  language?: Language;
  short_code?: ShortCode;
}

export enum ID {
  Country8945 = "country.8945",
  Place2107633 = "place.2107633",
  Postcode118513 = "postcode.118513",
  Region173297 = "region.173297",
}

export enum Language {
  Es = "es",
}

export enum ShortCode {
  Ve = "ve",
  VeS = "VE-S",
}

export enum Wikidata {
  Q3471395 = "Q3471395",
  Q41144 = "Q41144",
  Q717 = "Q717",
}

export interface Geometry {
  coordinates: number[];
  type: string;
}

export interface Properties {
  foursquare: string;
  landmark: boolean;
  category: string;
  address?: string;
}
